/*
  NOTE: This file is generated by "compiler/compile". Any changes made to it will be lost next compilation.

  Existing modules: 
  	* Admin
  	* Core
  	* Groups
  	* Player
  
  Existing callbacks: 
  	+ OnGameModeInit()
  	  __fmt_funcinc()
  	  OnFilterScriptExit()
  	  OnFilterScriptInit()
  	  OnGameModeExit()
  	  main()
  	  OnRconCommand(cmd[])
  	  @receivestring(const message[], const source[])
  	  @receivepacket(const packet[], size, const source[])
  	+ OnRconLoginAttempt(ip[], password[], success)
  	  OnObjectMoved(objectid)
  	  OnPlayerLeaveRaceCheckpoint(playerid)
  	  OnPlayerEnterRaceCheckpoint(playerid)
  	  OnPlayerUpdate(playerid)
  	+ OnPlayerConnect(playerid)
  	  OnPlayerLeaveCheckpoint(playerid)
  	  OnPlayerExitedMenu(playerid)
  	  OnPlayerRequestSpawn(playerid)
  	  OnPlayerRconLogin(playerid)
  	+ OnPlayerSpawn(playerid)
  	  OnPlayerEnterCheckpoint(playerid)
  	  OnPlayerClickMap(playerid, Float:fX, Float:fY, Float:fZ)
  	+ OnPlayerRequestClass(playerid, classid)
  	  OnPlayerClickPlayer(playerid, clickedplayerid, source)
  	  OnPlayerCommandText(playerid, cmdtext[])
  	  OnPlayerGiveDamage(playerid, damagedid, Float:amount, weaponid)
  	  OnDialogResponse(playerid, dialogid, response, listitem, inputtext[])
  	  OnEnterExitModShop(playerid, enterexit, interiorid)
  	  OnPlayerStreamOut(playerid, forplayerid)
  	  OnPlayerStreamIn(playerid, forplayerid)
  	  OnPlayerTakeDamage(playerid, issuerid, Float:amount, weaponid)
  	  OnPlayerDeath(playerid, killerid, reason)
  	  OnPlayerInteriorChange(playerid, newinteriorid, oldinteriorid)
  	  OnPlayerKeyStateChange(playerid, newkeys, oldkeys)
  	  OnPlayerStateChange(playerid, newstate, oldstate)
  	  OnPlayerObjectMoved(playerid, objectid)
  	  OnPlayerPickUpPickup(playerid, pickupid)
  	  OnPlayerDisconnect(playerid, reason)
  	  OnPlayerSelectedMenuRow(playerid, row)
  	  OnPlayerText(playerid, text[])
  	  OnPlayerExitVehicle(playerid, vehicleid)
  	  OnVehicleRespray(playerid, vehicleid, color1, color2)
  	  OnVehicleMod(playerid, vehicleid, componentid)
  	  OnPlayerEnterVehicle(playerid, vehicleid, ispassenger)
  	  OnVehiclePaintjob(playerid, vehicleid, paintjobid)
  	  OnVehicleSpawn(vehicleid)
  	  OnVehicleStreamOut(vehicleid, forplayerid)
  	  OnVehicleStreamIn(vehicleid, forplayerid)
  	  OnVehicleDeath(vehicleid, killerid)
  	  OnVehicleDamageStatusUpdate(vehicleid, playerid)
  	  OnUnoccupiedVehicleUpdate(vehicleid, playerid, passenger_seat)
*/

/****************************************************************************
                           WARNING! Headache below.
 ***************************************************************************/

#if !defined IN_COMPILE_SCRIPT
	#error You must use the compile script in the "compiler" folder.
#endif

const COMPILATION_TIMESTAMP = 1334144173;

#define PBP.  PBP_
#define PBP_DEFAULT_RETURN<%1>  DR@%1

enum PBP.e_MODULE {
	Name[7]
};

stock const
	PBP.Modules[][PBP.e_MODULE] = {
		{"Admin"},
		{"Core"},
		{"Groups"},
		{"Player"}
	}
;

#define CFG_MAX_PLAYERS 32

#define Admin. M0@
#define M0@INDEX  0
#define M0@OFFSET  (0 * PBP.MODULE_OFFSET_MULTIPLIER)
#define Core. M1@
#define M1@INDEX  1
#define M1@OFFSET  (1 * PBP.MODULE_OFFSET_MULTIPLIER)
#define Groups. M2@
#define M2@INDEX  2
#define M2@OFFSET  (2 * PBP.MODULE_OFFSET_MULTIPLIER)
#define Player. M3@
#define M3@INDEX  3
#define M3@OFFSET  (3 * PBP.MODULE_OFFSET_MULTIPLIER)

#tryinclude "header"

#if defined _inc_header
	#undef _inc_header
#endif

#if !defined PBP_MODULE_OFFSET_MULTIPLIER
	const PBP.MODULE_OFFSET_MULTIPLIER = 1000;
#endif


// header.inc

#define this. Groups.
#if defined _inc_header
	#undef _inc_header
#endif
#include "modules\Groups\header"
#undef _inc_header
#undef this
#define this. Admin.
#if defined _inc_header
	#undef _inc_header
#endif
#include "modules\Admin\header"
#undef _inc_header
#undef this
#define this. Core.
#if defined _inc_header
	#undef _inc_header
#endif
#include "modules\Core\header"
#undef _inc_header
#undef this
#define this. Player.
#if defined _inc_header
	#undef _inc_header
#endif
#include "modules\Player\header"
#undef _inc_header
#undef this

// callbacks.inc

#define this. Admin.
#if defined _inc_callbacks
	#undef _inc_callbacks
#endif
#include "modules\Admin\callbacks"
#undef _inc_callbacks
#undef this
#define this. Core.
#if defined _inc_callbacks
	#undef _inc_callbacks
#endif
#include "modules\Core\callbacks"
#undef _inc_callbacks
#undef this
#define this. Groups.
#if defined _inc_callbacks
	#undef _inc_callbacks
#endif
#include "modules\Groups\callbacks"
#undef _inc_callbacks
#undef this
#define this. Player.
#if defined _inc_callbacks
	#undef _inc_callbacks
#endif
#include "modules\Player\callbacks"
#undef _inc_callbacks
#undef this

// functions.inc

#define this. Admin.
#if defined _inc_functions
	#undef _inc_functions
#endif
#include "modules\Admin\functions"
#undef _inc_functions
#undef this
#define this. Core.
#if defined _inc_functions
	#undef _inc_functions
#endif
#include "modules\Core\functions"
#undef _inc_functions
#undef this
#define this. Groups.
#if defined _inc_functions
	#undef _inc_functions
#endif
#include "modules\Groups\functions"
#undef _inc_functions
#undef this
#define this. Player.
#if defined _inc_functions
	#undef _inc_functions
#endif
#include "modules\Player\functions"
#undef _inc_functions
#undef this

// commands.inc

#define this. Admin.
#if defined _inc_commands
	#undef _inc_commands
#endif
#include "modules\Admin\commands"
#undef _inc_commands
#undef this
#define this. Core.
#if defined _inc_commands
	#undef _inc_commands
#endif
#include "modules\Core\commands"
#undef _inc_commands
#undef this
#define this. Groups.
#if defined _inc_commands
	#undef _inc_commands
#endif
#include "modules\Groups\commands"
#undef _inc_commands
#undef this
#define this. Player.
#if defined _inc_commands
	#undef _inc_commands
#endif
#include "modules\Player\commands"
#undef _inc_commands
#undef this



main() {}

#if !defined OnGameModeInit
	#error Callback  "OnGameModeInit" is used, but not defined. Did you forget to include it?
#endif

public OnGameModeInit() {
	new PBP.ReturnValue
		#if defined DR@OnGameModeInit
			= PBP.DEFAULT_RETURN<OnGameModeInit>;
		#elseif defined ALS_R_GameModeInit
			= ALS_R_GameModeInit;
		#else
			= 1;
		#endif

	#define this. Core.
	#if defined _inc_OnGameModeInit
		#undef _inc_OnGameModeInit
	#endif
	#include "modules\Core\callbacks\OnGameModeInit"
	#undef _inc_OnGameModeInit
	#undef this
	#define this. Groups.
	#if defined _inc_OnGameModeInit
		#undef _inc_OnGameModeInit
	#endif
	#include "modules\Groups\callbacks\OnGameModeInit"
	#undef _inc_OnGameModeInit
	#undef this
	#define this. Player.
	#if defined _inc_OnGameModeInit
		#undef _inc_OnGameModeInit
	#endif
	#include "modules\Player\callbacks\OnGameModeInit"
	#undef _inc_OnGameModeInit
	#undef this

	return PBP.ReturnValue;
}

#if !defined OnPlayerConnect
	#error Callback  "OnPlayerConnect" is used, but not defined. Did you forget to include it?
#endif

public OnPlayerConnect(playerid) {
	new PBP.ReturnValue
		#if defined DR@OnPlayerConnect
			= PBP.DEFAULT_RETURN<OnPlayerConnect>;
		#elseif defined ALS_R_PlayerConnect
			= ALS_R_PlayerConnect;
		#else
			= 1;
		#endif

	#define this. Player.
	#if defined _inc_OnPlayerConnect
		#undef _inc_OnPlayerConnect
	#endif
	#include "modules\Player\callbacks\OnPlayerConnect"
	#undef _inc_OnPlayerConnect
	#undef this

	return PBP.ReturnValue;
}

#if !defined OnPlayerRequestClass
	#error Callback  "OnPlayerRequestClass" is used, but not defined. Did you forget to include it?
#endif

public OnPlayerRequestClass(playerid, classid) {
	new PBP.ReturnValue
		#if defined DR@OnPlayerRequestClass
			= PBP.DEFAULT_RETURN<OnPlayerRequestClass>;
		#elseif defined ALS_R_PlayerRequestClass
			= ALS_R_PlayerRequestClass;
		#else
			= 1;
		#endif

	#define this. Player.
	#if defined _inc_OnPlayerRequestClass
		#undef _inc_OnPlayerRequestClass
	#endif
	#include "modules\Player\callbacks\OnPlayerRequestClass"
	#undef _inc_OnPlayerRequestClass
	#undef this

	return PBP.ReturnValue;
}

#if !defined OnPlayerSpawn
	#error Callback  "OnPlayerSpawn" is used, but not defined. Did you forget to include it?
#endif

public OnPlayerSpawn(playerid) {
	new PBP.ReturnValue
		#if defined DR@OnPlayerSpawn
			= PBP.DEFAULT_RETURN<OnPlayerSpawn>;
		#elseif defined ALS_R_PlayerSpawn
			= ALS_R_PlayerSpawn;
		#else
			= 1;
		#endif

	#define this. Player.
	#if defined _inc_OnPlayerSpawn
		#undef _inc_OnPlayerSpawn
	#endif
	#include "modules\Player\callbacks\OnPlayerSpawn"
	#undef _inc_OnPlayerSpawn
	#undef this

	return PBP.ReturnValue;
}

#if !defined OnRconLoginAttempt
	#error Callback  "OnRconLoginAttempt" is used, but not defined. Did you forget to include it?
#endif

public OnRconLoginAttempt(ip[], password[], success) {
	new PBP.ReturnValue
		#if defined DR@OnRconLoginAttempt
			= PBP.DEFAULT_RETURN<OnRconLoginAttempt>;
		#elseif defined ALS_R_RconLoginAttempt
			= ALS_R_RconLoginAttempt;
		#else
			= 1;
		#endif

	#define this. Player.
	#if defined _inc_OnRconLoginAttempt
		#undef _inc_OnRconLoginAttempt
	#endif
	#include "modules\Player\callbacks\OnRconLoginAttempt"
	#undef _inc_OnRconLoginAttempt
	#undef this

	return PBP.ReturnValue;
}

