// Please be very careful with the layout of this file. Only change strings on the right side.
// Do not change comments or strings on the left side.

"Hello world!" = "¡Hola, mundo!"

// Greeting message
"What's up?" = "¿Qué pasa?"

"I like \"quotes\"." = "Me gusta \"cotizaciones\"."

"Also new\nlines, and\ttabs." = "También las líneas\nnuevas y\tpestañas."

"* Set a player's admin level." = "* Ajuste el nivel de administrador de un jugador."

"* Usage: /setlevel [player] [level]" = "* Uso: /setlevel [jugador] [nivel]"

"* Invalid player." = "* El jugador no válido."

"* You may only change the level of players with a level lower than yours." = "* You can only change the level of the players with a lower level than yours."

"* Invalid level." = "* El nivel no válido."

"* %P%C already has that level." = "* %P%C ya tiene ese nivel."

"* You set the level of %P%C to %s (%d)." = "* Ha ajustado el nivel de %P%C a %s (%d)."

"ERROR: Please log in first." = "ERROR: Por favor, acceda primero."

"Quit" = "Dejar"

"Are you sure you want to quit the server?" = "¿Está seguro que desea dejar el servidor?"

"Cancel" = "Cancelar"

"* You were kicked from the server because of too many failed log in attempts." = "* Has sido expulsado del servidor debido a demasiados registro que presenta errores en los intentos."

"Invalid password. You have %d more %s, then you'll get kicked." = "Contraseña no válida. Tienes %d %s más, entonces usted obtendrá patada."

"attempt" = "intento"

// Plural of attempt
"attempts" = "intentos"

"Log in failed" = "Iniciar sesión fallida"

"Retry" = "Reintentar"

"Log in" = "Iniciar la sesión"

"This nickname is registered. Please log in or come back with another nickname.\n\nEnter your password:" = "Este apodo se ha registrado. Por favor, inicie sesión o regresar con otro apodo.\n\nIngrese su contraseña:"

"OK" = "OK"

"Success" = "Éxito"

"This nickname is now registered!" = "Este apodo se registra ahora!"

"Cool" = "Genial"

"Failed to register. Try with another nickname or contact server management if the problem persists." = "No se ha podido registrar. Pruebe con otro apodo o contacto de la administración de servidores si el problema persiste."

"Register" = "Registro"

"You must register this nickname before playing.\n\nEnter a password:" = "Debe registrar este apodo antes de jugar.\n\nlntroduzca una contraseña:"

"Set a player's admin level." = "Ajuste el nivel de administrador de un jugador."

"* %P%C was promoted to %L by %P%C." = "* %P%C fue ascendido a %L por %P%C."

"* %P%C was demoted to %L by %P%C." = "* %P%C fue degradado a %L por %P%C."

"You are now logged in!" = "Ahora está conectado!"

"* You were automatically logged in." = "* Tí había iniciado una sesión de forma automática pulg."

"* Set your language." = "* Selección tu idioma."

"Set your language." = "Selección tu idioma."

"Moderator" = "Moderador"

"Administrator" = "Administrador"

"Management" = "Gerencia"

"RCON Administrator" = "Administrador de RCON"

"Nothing" = "Nada"

"* Change your nickname." = "* Cambia tu apodo."

"* Usage: /setname [name]" = "* Uso: /setname [nombre]"

"* Your nickname was successfully changed to %s." = "* Tu apodo fue cambiado con éxito para %s."

"* Invalid name." = "* Nombre no válido."

"See a list of available commands." = "Ver una lista de comandos disponibles."

"Commands" = "Comandos"

"Close" = "Cerrar"

"< Back" = "< Espalda"

"Next >" = "Próximo >"

"View information about a certain command." = "Ver información sobre un determinado comando."

"* View information about a certain command." = "* Ver información sobre un determinado comando."

"* Usage: /help [command]" = "* Uso: /help [comando]"

"* Invalid command." = "* Comando no válido."

"Config editor - Select category" = "Editor Configuración - Seleccione una categoría"

"Config editor - Select entry" = "Editor Configuración - Seleccione una entrada"

"Back" = "Espalda"

"You are editing %S.\n\nCurrent value: %s" = "Estás editando %S.\n\nValor actual: %s"

"Config editor - Edit entry" = "Editor Configuración - Editar entrada"

"Show the config editor." = "Mostrar el editor de configuración."

"* Show the config editor." = "* Mostrar el editor de configuración."

"Armour" = "Blindaje"
