// Please be very careful with the layout of this file. Only change strings on the right side.
// Do not change comments or strings on the left side.
// Translations assisted by 'Assassins Creed Fan'

"Hello world!" = "Hallo werelds!"

// Greeting message
"What's up?" = "Hoe gaat het?"

"I like \"quotes\"." = "Ik hou van \"citaten\"."

"Also new\nlines, and\ttabs." = "Ook nieuwe\nlijnen, en\ttabbladen."

"* Set a player's admin level." = "* Rangschik een speler zijn administratie niveau."

"* Usage: /setlevel [player] [level]" = "* Gebruik: /setlevel [speler] [niveau]"

"* Invalid player." = "* Ongeldig speler."

"* You may only change the level of players with a level lower than yours." = "* Je mag alleen het niveau van spelers veranderen met een lager level dan jou."

"* Invalid level." = "* Ongeldig niveau."

"* %P%C already has that level." = "* %P%C heeft dit level al."

"* You set the level of %P%C to %s (%d)." = "* Je hebt %P%C zijn level veranderd naar %s (%d)."

"ERROR: Please log in first." = "FOUTMELDING: Log alsjeblieft eerst in."

"Quit" = "Stoppen"

"Are you sure you want to quit the server?" = "Ben je zeker dat je de server wilt verlaten?"

"Cancel" = "Afbreken"

"* You were kicked from the server because of too many failed log in attempts." = "* Je bent van de server getrapt omdat je té veel incorrecte aanmeld pogingen hebt gedaan."

"Invalid password. You have %d more %s, then you'll get kicked." = "Ongeldig wachtwoord. Je hebt nog %d meer %s, anders wordt je getrapt."

"attempt" = "probeer"

// Plural of attempt
"attempts" = "proberen"

"Log in failed" = "Inloggen gefaald"

"Retry" = "Probeer opnieuw"

"Log in" = "Aanmelden"

"This nickname is registered. Please log in or come back with another nickname.\n\nEnter your password:" = "Die bijnaam is al geregistreerd. Meld je alsjeblieft aan met een andere bijnaam.\n\nVul je wachtwoord in:"

"OK" = "OK"

"Success" = "Succes"

"This nickname is now registered!" = "De bijnaam is nu geregistreerd!"

"Cool" = "Koud"

"Failed to register. Try with another nickname or contact server management if the problem persists." = "Het is mislukt om te registreren. Probeer een andere bijnaam, of contacteer het management van de server als het probleem blijft aanhouden."

"Register" = "Registreer"

"You must register this nickname before playing.\n\nEnter a password:" = "Je moet deze bijnaam registreren voordat je kunt spelen.\n\nVul een wachtwoord in:"

"Set a player's admin level." = "Rangschik een speler zijn administratie niveau."

"* %P%C was promoted to %L by %P%C." = "* %P%C is gepromoveerd naar %L door %P%C."

"* %P%C was demoted to %L by %P%C." = "* %P%C is gedegradeerd naar %L door %P%C."

"You are now logged in!" = "Je bent nu ingelogd!"

"* You were automatically logged in." = "* Je bent automatisch ingelogd."

"* Set your language." = "* Stel je taal in."

"Set your language." = "Stel je taal in."

"Moderator" = "Moderator"

"Administrator" = "Beheerder"

"Management" = "Beheer"

"RCON Administrator" = "RCON Beheerder"

"Nothing" = "Niks"

"* Change your nickname." = "* Verander je bijnaam."

"* Usage: /setname [name]" = "* Gebruik: /setname [naam]"

"* Your nickname was successfully changed to %s." = "* Je bijnaam is succesvol veranderd naar %s."

"* Invalid name." = "* Ongeldig naan."

"See a list of available commands." = "Bekijk een lijst van de beschikbare commando's."

"Commands" = "Commando's"

"Close" = "Sluiten"

"< Back" = "< Terug"

"Next >" = "Volgende >"

"View information about a certain command." = "Bekijk info over een bepaald commando."

"* View information about a certain command." = "* Bekijk info over een bepaald commando."

"* Usage: /help [command]" = "* Gebruik: /help [commando]"

"* Invalid command." = "* Ongeldig commando."

"Config editor - Select category" = "Configuratie bijwerker - Selecteer categorie"

"Config editor - Select entry" = "Configuratie bijwerker - Selecteer entree"

"Back" = "Terug"

// I'm unsure about the one below, not too sure about the usage.
"You are editing %S.\n\nCurrent value: %s" = "U bewerkt %S.\n\nHuidige waarde: %s"

"Config editor - Edit entry" = "Configuratie bijwerker - Bewerk entree"

"Show the config editor." = "Bekijk de configuratie bijwerker."

"* Show the config editor." = "* Bekijk de configuratie bijwerker."

"Armour" = "Pantser"
