// Please be very careful with the layout of this file. Only change strings on the right side.
// Do not change comments or strings on the left side.

"Hello world!" = "Salut lume!"

// Greeting message
"What's up?" = "Care-i treaba?"

"I like \"quotes\"." = "Imi plac \"citatele\"."

"Also new\nlines, and\ttabs." = "De asemenea linii\nnoi, si\tfile."

"* Set a player's admin level." = "* Seteaza nivelul unui jucator."

"* Usage: /setlevel [player] [level]" = "* Folosire: /setlevel [jucator] [nivel]"

"* Invalid player." = "* Jucator invalid."

"* You may only change the level of players with a level lower than yours." = "* Poti schimba nivelul jucatorilor doar daca au un nivel mai mic decat al tau."

"* Invalid level." = "* Nivel invalid."

"* %P%C already has that level." = "* %P%C are acel nivel deja."

"* You set the level of %P%C to %s (%d)." = "* Ai setat nivelul lui %P%C in %s (%d)."

"ERROR: Please log in first." = "EROARE: Logheaza-te mai intai."

"Quit" = "Parasire"

"Are you sure you want to quit the server?" = "Esti sigur ca vrei sa parasesti serverul?"

"Cancel" = "Anulare"

"* You were kicked from the server because of too many failed log in attempts." = "* Ai fost scos de pe server din cauza multor logari nereusite."

"Invalid password. You have %d more %s, then you'll get kicked." = "Parola incorecta. Mai ai %d %s, apoi vei fi scos."

"attempt" = "incercare"

// Plural of attempt
"attempts" = "incercari"

"Log in failed" = "Logare nereusita"

"Retry" = "Reincarcare"

"Log in" = "Logare"

"This nickname is registered. Please log in or come back with another nickname.\n\nEnter your password:" = "Aceasta nume este inregistrat. Te rugam sa te loghezi sau sa reintri cu un alt nume.\n\nInsereaza parola:"

"OK" = "OK"

"Success" = "Succes"

"This nickname is now registered!" = "Acest nume este inregistrat acum!"

"Cool" = "Misto"

"Failed to register. Try with another nickname or contact server management if the problem persists." = "Inregistrare nereusita. Incearca cu un alt nume, sau contacteaza un administrator daca problema persista."

"Register" = "Inregistrare"

"You must register this nickname before playing.\n\nEnter a password:" = "Trebuie sa te inregistrezi pentru a juca.\n\nInsereaza parola:"

"Set a player's admin level." = "Seteaza nivelul unui administrator."

"* %P%C was promoted to %L by %P%C." = "* %P%C a fost promovat de catre %P%C la nivelul %L."

"* %P%C was demoted to %L by %P%C." = "* %P%C a fost retrogradat de catre %P%C la nivelul %L."

"You are now logged in!" = "Esti logat acum!"

"* You were automatically logged in." = "* Ai fost logat automat."

"* Set your language." = "* Selecteaza limba."

"Set your language." = "Selecteaza limba."

"Moderator" = "Moderator"

"Administrator" = "Administrator"

"Management" = "Administrare"

"RCON Administrator" = "RCON Administrator"

"Nothing" = "Nimic"

"* Change your nickname." = "* Schimba-ti numele."

"* Usage: /setname [name]" = "* Folosire: /setname [nume]"

"* Your nickname was successfully changed to %s." = "* Numele tau a fost schimbat in %s cu succes."

"* Invalid name." = "* Nume invalid."

"See a list of available commands." = "Vezi o lista cu comenzi disponibile."

"Commands" = "Comenzi"

"Close" = "Inchide"

"< Back" = "< Inapoi"

"Next >" = "Urmatorul >"

"View information about a certain command." = "Vizualiza informatii despre o anumita comanda."

"* View information about a certain command." = "* Vizualiza informatii despre o anumita comanda."

"* Usage: /help [command]" = "* Folosire: /help [comanda]"

"* Invalid command." = "* Comanda invalida."

"Config editor - Select category" = "Editor Configurare - Selectati categoria"

"Config editor - Select entry" = "Editor Configurare - Selectati intrarea"

"Back" = "Inapoi"

"You are editing %S.\n\nCurrent value: %s" = "Pe care o editati %S.\n\nValoarea curenta: %s"

"Config editor - Edit entry" = "Editor Configurare - Editare intrare"

"Show the config editor." = "Arata editor de configurare."

"* Show the config editor." = "* Arata editor de configurare."

"Armour" = "Blindaj"
