// Please be very careful with the layout of this file. Only change strings on the right side.
// Do not change comments or strings on the left side.

"Hello world!" = "Hej världen!"

// Greeting message
"What's up?" = "Vad händer?"

"I like \"quotes\"." = "Jag gillar \"citationstecken\"."

"Also new\nlines, and\ttabs." = "Även nya\nrader, och\ttabbar."

"* Set a player's admin level." = "* Ändra en spelares admin nivå."

"* Usage: /setlevel [player] [level]" = "* Användning: /setlevel [spelare] [nivå]"

"* Invalid player." = "* Ogiltig spelare."

"* You may only change the level of players with a level lower than yours." = "* Du får endast ändra nivån för spelare med en nivå lägre än din."

"* Invalid level." = "* Ogiltig nivå."

"* %P%C already has that level." = "* %P%C har redan den nivån."

"* You set the level of %P%C to %s (%d)." = "* Du ändrade nivån för %P%C till %s (%d)."

"ERROR: Please log in first." = "FEL: Vänligen logga in först."

"Quit" = "Avsluta"

"Are you sure you want to quit the server?" = "Är du säker att du vill lämna servern?"

"Cancel" = "Avbryt"

"* You were kicked from the server because of too many failed log in attempts." = "* Du blev kickad från servern pga. för många misslyckade inloggningsförsök."

"Invalid password. You have %d more %s, then you'll get kicked." = "Ogiltigt lösenord. Du har %d %s kvar innan du blir kickad."

"attempt" = "försök"

// Plural of attempt
"attempts" = "försök"

"Log in failed" = "Inloggning misslyckades"

"Retry" = "Försök igen"

"Log in" = "Logga in"

"This nickname is registered. Please log in or come back with another nickname.\n\nEnter your password:" = "Det här namnet är registrerat. Vänligen logga in eller kom tillbaka med ett annat namn.\n\nAnge ditt lösenord:"

"OK" = "OK"

"Success" = "Succé"

"This nickname is now registered!" = "Det här namnet är nu registrerat!"

"Cool" = "Häftigt"

"Failed to register. Try with another nickname or contact server management if the problem persists." = "Misslyckades att registrera. Försök med ett annat namn eller kontakta ansvariga om problemet kvarstår."

"Register" = "Registrera"

"You must register this nickname before playing.\n\nEnter a password:" = "Du måste registrera det här namnet innan du kan spela.\n\nAnge ett lösenord:"

"* %P%C was promoted to %L by %P%C." = "* %P%C blev befodrad till %L av %P%C."

"* %P%C was demoted to %L by %P%C." = "* %P%C blev degraderad till %L av %P%C."

"You are now logged in!" = "Du är nu inloggad!"
