// Please be very careful with the layout of this file. Only change strings on the right side.
// Do not change comments or strings on the left side.

"Moderator" = "Moderator"

"Administrator" = "Administrator"

"Management" = "Management"

"RCON Administrator" = "RCON Administrator"

"Set a player's admin level." = "Set a player's admin level."

"* Set a player's admin level." = "* Set a player's admin level."

"* Usage: /setlevel [player] [level]" = "* Usage: /setlevel [player] [level]"

"* Invalid player." = "* Invalid player."

"* You may only change the level of players with a level lower than yours." = "* You may only change the level of players with a level lower than yours."

"* Invalid level." = "* Invalid level."

"* %P%C already has that level." = "* %P%C already has that level."

"* You set the level of %P%C to %s (%d)." = "* You set the level of %P%C to %s (%d)."

"Commands" = "Commands"

"OK" = "OK"

"Close" = "Close"

"Next >" = "Next >"

"< Back" = "< Back"

"See a list of available commands." = "See a list of available commands."

"View information about a certain command." = "View information about a certain command."

"* View information about a certain command." = "* View information about a certain command."

"* Usage: /help [command]" = "* Usage: /help [command]"

"* Invalid command." = "* Invalid command."

"Config editor - Select category" = "Config editor - Select category"

"Config editor - Select entry" = "Config editor - Select entry"

"Back" = "Back"

"You are editing %S.\n\nCurrent value: %s" = "You are editing %S.\n\nCurrent value: %s"

"Config editor - Edit entry" = "Config editor - Edit entry"

"Cancel" = "Cancel"

"Show the config editor." = "Show the config editor."

"* Show the config editor." = "* Show the config editor."

"Set your language." = "Set your language."

"* Set your language." = "* Set your language."

"ERROR: Please log in first." = "ERROR: Please log in first."

"Log in" = "Log in"

"This nickname is registered. Please log in or come back with another nickname.\n\nEnter your password:" = "This nickname is registered. Please log in or come back with another nickname.\n\nEnter your password:"

"Register" = "Register"

"You must register this nickname before playing.\n\nEnter a password:" = "You must register this nickname before playing.\n\nEnter a password:"

"Nothing" = "Nothing"

"* %P%C was promoted to %L by %P%C." = "* %P%C was promoted to %L by %P%C."

"* %P%C was demoted to %L by %P%C." = "* %P%C was demoted to %L by %P%C."

"Armour" = "Armour"

"Quit" = "Quit"

"Are you sure you want to quit the server?" = "Are you sure you want to quit the server?"

"* You were kicked from the server because of too many failed log in attempts." = "* You were kicked from the server because of too many failed log in attempts."

"Invalid password. You have %d more %s, then you'll get kicked." = "Invalid password. You have %d more %s, then you'll get kicked."

"attempt" = "attempt"

// Plural of attempt
"attempts" = "attempts"

"Log in failed" = "Log in failed"

"Retry" = "Retry"

"Success" = "Success"

"This nickname is now registered!" = "This nickname is now registered!"

"Cool" = "Cool"

"Failed to register. Try with another nickname or contact server management if the problem persists." = "Failed to register. Try with another nickname or contact server management if the problem persists."

"* You were automatically logged in." = "* You were automatically logged in."

"You are now logged in!" = "You are now logged in!"
